spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.application.name=backend-service
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
