spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.application.name=backend-service
server.port=8080

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
