app.environment=PRODUCTION
app.description=Production Live System
logging.level.root=INFO

spring.datasource.url=jdbc:h2:file:./data/portal;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=false
